### ISSUE TITLE
Can't setup ffsync on android

### ISSUE THREAD

**Issue by Josue-T** [YunoHost-Apps/syncserver-rs_ynh#46]
### Describe the bug

I can't setup the synchronisation on android following the doc https://github.com/YunoHost-Apps/syncserver-rs_ynh/blob/master/doc/POST_INSTALL.md#configure-firefox-based-browsers-on-android

### Context

- Hardware: Self hosted server. (AMD64 architecture)
- Yunohost version: 11.2.14
- Firefox android version: 126
- Also tested with fenec fdroid version 125

### Steps to reproduce

- Floow the step from here: https://github.com/YunoHost-Apps/syncserver-rs_ynh/blob/master/doc/POST_INSTALL.md#configure-firefox-based-browsers-on-android
- At some point you will have a page like this for the authentication
![Screenshot_20240609-115312_Fennec](https://github.com/YunoHost-Apps/syncserver-rs_ynh/assets/7387681/c2432c05-bdd2-4d74-870c-7a6dba2b8349)

And after 

### Expected behaviour

After the authentication, the webview should be closed and the sychronisation should start.

### Current behaviour

After the authentication we end up with this page and so no account setup are done.

![Screenshot_20240609-115854_Fennec](https://github.com/YunoHost-Apps/syncserver-rs_ynh/assets/7387681/35e8bfc4-3f4d-45c8-bea4-eee7a78fb473)

### Logs

I have this log from the server

```
Jun 09 10:12:45.240 INFO {"ua":"125.0","ua.os.family":"Other","ua.browser.ver":"125.0","ua.name":"Firefox","uri.path":"/1.0/sync/.well-known/fxa-client-configuration","ua.os.ver":"12","ua.browser.family":"Firefox","uri.method":"GET"}
Jun 09 10:12:45.268 INFO {"ua.browser.family":"Firefox","uri.path":"/1.0/sync/.well-known/fxa-client-configuration","ua.browser.ver":"125.0","uri.method":"GET","ua":"125.0","ua.os.family":"Other","ua.os.ver":"12","ua.name":"Firefox"}
Jun 09 10:12:45.290 INFO {"ua.os.family":"Other","ua.name":"Firefox","ua.browser.ver":"125.0","ua.browser.family":"Firefox","ua":"125.0","uri.path":"/1.0/sync/.well-known/fxa-client-configuration","uri.method":"GET","ua.os.ver":"12"}
```

with ADB I've this log which cleary mention that there are an issue.

```
06-09 11:57:56.277 13999 13999 I FirefoxAccountStateMachine: Sync is enabled
06-09 11:57:56.670 13999 14177 I FirefoxAccountStateMachine: Processing event 'mozilla.components.service.fxa.manager.Event$Account$Start@1f55b8c' for state Idle(accountState=mozilla.components.service.fxa.manager.AccountState$NotAuthenticated@4599024). Next state is Active(progressState=Initializing)
06-09 11:57:56.722 13999 14177 I FirefoxAccount: Registering persistence callback
06-09 11:57:56.722 13999 14177 I FirefoxAccountStateMachine: Ran 'mozilla.components.service.fxa.manager.Event$Account$Start@1f55b8c' side-effects for state Active(progressState=Initializing), got successive event mozilla.components.service.fxa.manager.Event$Progress$AccountNotFound@ee8164a
06-09 11:57:56.741 13999 14177 I FirefoxAccountStateMachine: Processing event 'mozilla.components.service.fxa.manager.Event$Progress$AccountNotFound@ee8164a' for state Active(progressState=Initializing). Next state is Idle(accountState=mozilla.components.service.fxa.manager.AccountState$NotAuthenticated@4599024)
06-09 11:58:01.488 13999 14034 I FxSuggestIngestionScheduler: Canceling periodic ingestion for new suggestions
06-09 11:58:05.131 13999 14177 W FirefoxAccountStateMachine: Got invalid event 'mozilla.components.service.fxa.manager.Event$Progress$CancelAuth@be0b4bd' for state Idle(accountState=mozilla.components.service.fxa.manager.AccountState$NotAuthenticated@4599024).
06-09 11:58:05.134 13999 14177 I FirefoxAccountStateMachine: Processing event 'BeginEmailFlow(entrypoint=SettingsMenu)' for state Idle(accountState=mozilla.components.service.fxa.manager.AccountState$NotAuthenticated@4599024). Next state is Active(progressState=BeginningAuthentication)
06-09 11:58:05.134 13999 14177 I FirefoxAccountStateMachine: withRetries: attempt 1/3
06-09 11:58:05.136 13999 14038 I FirefoxAccount: Executing: begin oauth flow
06-09 11:58:05.211 13999 14038 E FirefoxAccount: Error while running: begin oauth flow
06-09 11:58:05.211 13999 14038 E FirefoxAccount: mozilla.appservices.fxaclient.FxaException$Other: other error
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.read(fxa_client.kt:4)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.read(fxa_client.kt:1)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverter$DefaultImpls.liftFromRustBuffer(fxa_client.kt:14)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(fxa_client.kt:7)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.liftFromRustBuffer(fxa_client.kt:2)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.liftFromRustBuffer(fxa_client.kt:1)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterRustBuffer$DefaultImpls.lift(fxa_client.kt:7)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.lift(fxa_client.kt:3)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.lift(fxa_client.kt:2)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaException$ErrorHandler.lift(fxa_client.kt:2)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaException$ErrorHandler.lift(fxa_client.kt:1)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.Fxa_clientKt.checkCallStatus(fxa_client.kt:75)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.Fxa_clientKt.access$checkCallStatus(fxa_client.kt:1)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FirefoxAccount.beginOauthFlow(fxa_client.kt:81)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient$beginOAuthFlow$1.invoke(FxaClient.kt:2)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient$beginOAuthFlow$1.invoke(FxaClient.kt:1)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient.withMetrics(FxaClient.kt:16)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient.beginOAuthFlow(FxaClient.kt:17)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$beginOAuthFlow$2$2.invokeSuspend(FirefoxAccount.kt:29)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$beginOAuthFlow$2$2.invoke(FirefoxAccount.kt:11)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:6)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:23)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$beginOAuthFlow$2.invokeSuspend(FirefoxAccount.kt:45)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
06-09 11:58:05.211 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
06-09 11:58:05.212 13999 14177 I FirefoxAccountStateMachine: withRetries: attempt 2/3
06-09 11:58:05.213 13999 14038 I FirefoxAccount: Executing: begin oauth flow
06-09 11:58:05.232 13999 14038 E FirefoxAccount: Error while running: begin oauth flow
06-09 11:58:05.232 13999 14038 E FirefoxAccount: mozilla.appservices.fxaclient.FxaException$Other: other error
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.read(fxa_client.kt:4)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.read(fxa_client.kt:1)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverter$DefaultImpls.liftFromRustBuffer(fxa_client.kt:14)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(fxa_client.kt:7)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.liftFromRustBuffer(fxa_client.kt:2)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.liftFromRustBuffer(fxa_client.kt:1)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterRustBuffer$DefaultImpls.lift(fxa_client.kt:7)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.lift(fxa_client.kt:3)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.lift(fxa_client.kt:2)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaException$ErrorHandler.lift(fxa_client.kt:2)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaException$ErrorHandler.lift(fxa_client.kt:1)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.Fxa_clientKt.checkCallStatus(fxa_client.kt:75)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.Fxa_clientKt.access$checkCallStatus(fxa_client.kt:1)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FirefoxAccount.beginOauthFlow(fxa_client.kt:81)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient$beginOAuthFlow$1.invoke(FxaClient.kt:2)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient$beginOAuthFlow$1.invoke(FxaClient.kt:1)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient.withMetrics(FxaClient.kt:16)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient.beginOAuthFlow(FxaClient.kt:17)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$beginOAuthFlow$2$2.invokeSuspend(FirefoxAccount.kt:29)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$beginOAuthFlow$2$2.invoke(FirefoxAccount.kt:11)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:6)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:23)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$beginOAuthFlow$2.invokeSuspend(FirefoxAccount.kt:45)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
06-09 11:58:05.232 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
06-09 11:58:05.233 13999 14177 I FirefoxAccountStateMachine: withRetries: attempt 3/3
06-09 11:58:05.234 13999 14038 I FirefoxAccount: Executing: begin oauth flow
06-09 11:58:05.253 13999 14038 E FirefoxAccount: Error while running: begin oauth flow
06-09 11:58:05.253 13999 14038 E FirefoxAccount: mozilla.appservices.fxaclient.FxaException$Other: other error
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.read(fxa_client.kt:4)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.read(fxa_client.kt:1)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverter$DefaultImpls.liftFromRustBuffer(fxa_client.kt:14)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(fxa_client.kt:7)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.liftFromRustBuffer(fxa_client.kt:2)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.liftFromRustBuffer(fxa_client.kt:1)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterRustBuffer$DefaultImpls.lift(fxa_client.kt:7)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.lift(fxa_client.kt:3)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FfiConverterTypeFxaError.lift(fxa_client.kt:2)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaException$ErrorHandler.lift(fxa_client.kt:2)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaException$ErrorHandler.lift(fxa_client.kt:1)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.Fxa_clientKt.checkCallStatus(fxa_client.kt:75)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.Fxa_clientKt.access$checkCallStatus(fxa_client.kt:1)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FirefoxAccount.beginOauthFlow(fxa_client.kt:81)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient$beginOAuthFlow$1.invoke(FxaClient.kt:2)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient$beginOAuthFlow$1.invoke(FxaClient.kt:1)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient.withMetrics(FxaClient.kt:16)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.appservices.fxaclient.FxaClient.beginOAuthFlow(FxaClient.kt:17)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$beginOAuthFlow$2$2.invokeSuspend(FirefoxAccount.kt:29)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$beginOAuthFlow$2$2.invoke(FirefoxAccount.kt:11)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:6)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:23)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at mozilla.components.service.fxa.FirefoxAccount$beginOAuthFlow$2.invokeSuspend(FirefoxAccount.kt:45)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
06-09 11:58:05.253 13999 14038 E FirefoxAccount:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
```

As many time before the sychronisaiton from android was broken by ustream, my question would be firstly does someone are able to reproduce this issue or not, so we can see if it's an issue to my local setup or if it's more an upstream issue.

Note that when I remove the custom token server, it work well so it look like that it's this setting which broke somehting.

**Comment by orhtej2** [comment]
I must admit I was never able to set up sync on mobile. I tried to trace down what's the expected path in source code for Firefox for Android and was unable to do so. 🤷
